# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 789885110e8efe3e5766b662e265d063990a34cbe6aeac12a9138c24c35f0bcf4953ba102faa0853c675f544b9d60c94e9bc585c7513f070396da106c82c6f4d

test:
  secret_key_base: b10b70594ec428170042aefd5448aad6cc02fd12429bea1a3469a94116939ce6b9b0a2b32b4efc981a6d4b071b33c66cafde3a623f0c80b7d41b783f96edbe6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
